### ISSUE TITLE
Make it easy to use https/ssl form submissions. 

### ISSUE THREAD

**Issue by espaan** [zikula-ev/Formicula#31]
I have not really tried yet, but read in the forum a while back that ssl/https submissions do not work. It might be good to have it possible to enable ssl for certain forms.

The forum topic in which this was discussed: http://support.zikula.de/module-CMS_Support_Forum-viewtopic-topic-30843-start-0.htm

So with options:
- All forms SLL enabled to ensure personal information is kept private
- Specify a comma sepearated list of forms that go with SSL enabled.
- Do nothing (backwards compatible, in the case you already have a full SSL website, or you have no SSL certificate so should be kept http://)
- Provide a link to the homepage with explicit SSL disabled at the confirm template yes/no

A list of forms in the admin section with a short description would then also be very convenient, see #37

**Comment by Guite** [comment]
Generally there is nothing preventing using Formicula using HTTPS. Closing.
