### ISSUE TITLE
Bug: datepicker + short url + captcha

### ISSUE THREAD

**Issue by snowcrack** [zikula-ev/Formicula#42]
Hi guys,

I found a bug in template nr. 4 (3_userform.html)

In this template there is a datepicker. In combination with short urls there is a problem.

If you answer the captcha once wrong, by the next try the system will tell you that your answer is wrong, even if it is right.

You only can send the form, if you reload the page and fill out all again.

The combination is: datepicker + short url + you answer the captcha once wrong.

best regards,

snowcrack

**Comment by Guite** [comment]
This is fixed as part of #64. Since the forms are now handled by Symfony forms, the url structure is different now.
