### ISSUE TITLE
Formicula calls function missing in 1.4.x

### ISSUE THREAD

**Issue by pheski** [zikula-ev/Formicula#61]
Formicula 3.1.1 in Zikula 1.4 gives the following error when using a form:

Fatal error: Call to undefined method DataUtil::censor() in 
.../modules/Formicula/lib/Formicula/Api/User.php on line 306

Zikula 1.3.6 (last distribution I used) had: /lib/util/Datautil.php where starting on line 515 there is a 'public static function' censor ($var) that seems to be gone in 1.4.x and I can find no language anywhere in 1.4.x about this public static function or censor().  

It looks to me as if Formicula is calling a missing function here:

/modules/Formicula/lib/Formicula/Api/User.php lines 306-313.

**Comment by pheski** [comment]
Any update?

**Comment by cmfcmf** [comment]
Hi @pheski, please see #62 for a fix. The function calls can safely be removed.
