### ISSUE TITLE
Since 4.00 the "add contact" page contains too many mandatory fields

### ISSUE THREAD

**Issue by MrMontesa** [zikula-ev/Formicula#67]
When adding a new contact in Formicula via Extensions admin page the page loads and contains 2 fieldsets. The upper one is about the new contact while the bottom one contains a form about the sender.
These 3 input fields are marked "mandatory" which doesnt make too much sense for me when adding a new contact.
Just compared the behavior with the old 3.1.2 Formicula where these 3 input fields are NOT mandatory.
Thanks for checking.

**Comment by MrMontesa** [comment]
The "(*)" items stating mandatory fields are indeed gone, but on submitting the form I still receive error message below each form field that the value cannot be empty.
![add contact-2016-11-01 09_55_33](https://cloud.githubusercontent.com/assets/600125/19884292/6534f2fe-a019-11e6-8927-0d1505087536.png)

**Comment by Guite** [comment]
Fixed in https://github.com/zikula-ev/Formicula/commit/0802878b7eaff419d7f4d494600138a68b36853f You probably need to empty the app cache to let the system reflect this change.

**Comment by MrMontesa** [comment]
While clearing the cache I recognized that formicula might have created a folder in wrong file hirarchy:
```

[user@host ~/htdocs/staging.amc-idstein/app/cache]$ ls -al
-rw-r-----  1 27915f16910  www   425 Sep  1 04:55 .htaccess
drwxrwxrwx  2 27915f16910  www   512 Nov  1 10:05 formicula
drwxr-x---  9 27915f16910  www  1024 Nov  1 10:31 prod

```

Other than that, I do receive an SQL error when entering a new Contact.
```

[3/3] NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO formicula_contact (name, email, public, senderName, senderEmail, sendingSubject) VALUES (?, ?, ?, ?, ?, ?)' with params ["Sag Hallo", "Test@test.de", 1, null, null, null]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'senderName' cannot be null   +
```

**Comment by Guite** [comment]
The cache folder is correct.
About the error please create a new issue.
