### ISSUE TITLE
contact list does not show the nice little buttons any longer

### ISSUE THREAD

**Issue by MrMontesa** [zikula-ev/Formicula#68]
Just a small one.
Since upgrade to 4.0.0 the nice little buttons in contact overview list are gone and you only see text links.

Sreenshot before:
![auto- und motorrad-club idstein e v im adac-2016-11-01 10_02_59](https://cloud.githubusercontent.com/assets/600125/19884544/7c4046e6-a01a-11e6-94e1-98c0ebd1ffd8.png)

Screenhot after:
![view contacts-2016-11-01 09_57_34](https://cloud.githubusercontent.com/assets/600125/19884391/e4e2b482-a019-11e6-8742-a17be7d8b004.png)

**Comment by Guite** [comment]
There are icons beside the text. So what you want is that the text is not visible, but only the icons?

**Comment by MrMontesa** [comment]
I was under the impression that Zikula offers some default Icons for add/edit/delete to bring some corporate identity and coherence across different extensions. Thought that just the stylesheet for those icons was missing.

Anyway, I like the nice little "telling images" rather than text.
