### ISSUE TITLE
Error message: "Invalid bundle type detected for component Formicula" since 1.4.4 upgrade

### ISSUE THREAD

**Issue by MrMontesa** [zikula-ev/Formicula#71]
I did a testupgrade from 1.4.3 where everything was working as expected to 1.4.4.
Since then I do receive the following error message in /extensions/module/list

`Invalid bundle type detected for component Formicula`

Other than that, Formicula seems to work fine. At least I was able to activate it again.

Edit: Same applies for PostCalendar so this might be a core issue rather than a formicula one.

**Comment by craigh** [comment]
duplicate of https://github.com/zikula/core/issues/3182 probably?

**Comment by MrMontesa** [comment]
Exactly!
